### PR TITLE
Add support for STM32G0

### PR DESCRIPTION
**Pull request by pavel-demin**

### CODE REVIEW

**Review by tgree — CHANGES_REQUESTED** [review]
Hi, and thanks for the pull request!  I apologize for the late reply!

It looks like STM32G0x1 is documented in RM0444 and STM32G0x0 is documented in RM0454.  After looking at RM0454 it seems to me that the G0x0 and G0x1 GPIO default settings are identical.  The current regex will pick them both up, but it might be better to rename the 'RM0444' key to 'RM0444_RM0454' or something like that.  Alternatively, you could change the regex to only match the G0 type you are interested in or duplicate the settings for the other RM, but I don't think that is necessary.

**Comment by pavel-demin** [comment]
I've renamed  the 'RM0444' key to 'RM0444_RM0454'.

**Review by tgree — APPROVED** [review]

**Comment by tgree** [comment]
Merged!  Thanks for the contribution!

**Comment by tgree** [comment]
If you are interested, thanks to some upstream modm-devices work, stm_layout is now pip-installable as a standard tool, e.g.:
```
pip3 install stm_layout
stm_layout -c stm32g030k6t6
```
So no need to deal with the git repo and manual 'make' installation if you don't want to!

**Pull request merged**
